### ISSUE TITLE
Замечания по 8.1

### ISSUE THREAD

**Issue by sergey-shambir** [knyazsergei/lab8#1]
- Смысл "animate.h" неясен
- не надо объявлять структуры через ```typedef struct Wheel {} Wheel;```, это сишная конструкция. Можно просто ```struct Wheel {};```, в C++ будет то же самое. Только в C перед именем структуры приходится добавлять ```struct```.
- есть закоментрованный код в структуре Car, надо убрать
- в коде есть new, но нет delete, похоже очисткой памяти никто не заботиться - не барское дело память беречь =)
- в ```createSprite``` лучше передавать класс ```std::string```, а не просто указатель на const char, в C++ лучше использовать средства языка C++ (по крайней мере, пока они работают хорошо, а не как <iostream> в реализации от Microsoft)

**Comment by knyazsergei** [comment]
Замечания поправил

**Comment by sergey-shambir** [comment]
- не надо коммитить pdb, ilk и прочие продукты сборки, пора настроить .gitignore и удалить эти файлы, сохранив это изменение в git. Тогда он прекратит их отслеживать.
- Смысл "animate.h" неясен
- не надо объявлять структуры через ```typedef struct Car {} Car ;```
- магические числа в moveWheels, нужны именованные константы
- надо также прочитать про Самую Главную Проблему здесь: https://github.com/AnatolyKorablyov/TP_lab_8.1/issues/1

**Comment by knyazsergei** [comment]
поправил

**Comment by sergey-shambir** [comment]
Так-то константы ```static const float shiftWheelXFirst = 0.275;``` следовало бы назвать не так, как пременные (обычно FIRST_WHEEL_X и SECOND_WHEEL_X). Тем не менее, принято.
